# Generated by Django 4.2.2 on 2023-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy_market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketclosingdata",
            name="hour",
            field=models.CharField(default="1:00", max_length=5),
            preserve_default=False,
        ),
    ]
