# Generated by Django 4.2.2 on 2023-06-10 12:52

from django.db import migrations, models
import energy_market.models


class Migration(migrations.Migration):
    dependencies = [
        ("energy_market", "0002_marketclosingdata_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketclosingdata",
            name="date",
            field=models.CharField(
                max_length=10, validators=[energy_market.models.validate_date_format]
            ),
        ),
    ]
